function Toy(name,imgSrcs,category,price)
{
this.name=name;
this.imgSrcs=imgSrcs;
this.category=category;
this.price=price;
}
var toys=[];//size not declared
var toy;
var imgSrcs=[];
function initializeToys()
{
//cars and tracks
imgSrcs.push("img/cars and tracks/turbos_124_remote_control_benz_sls_licensed_toys_car_red_1.jpg");
imgSrcs.push("img/cars and tracks/turbos_124_remote_control_benz_sls_licensed_toys_car_red_2.jpg");
imgSrcs.push("img/cars and tracks/turbos_124_remote_control_benz_sls_licensed_toys_car_red_3.jpg");
imgSrcs.push("img/cars and tracks/turbos_124_remote_control_benz_sls_licensed_toys_car_red_4.jpg");
imgSrcs.push("img/cars and tracks/turbos_124_remote_control_benz_sls_licensed_toys_car_red_5.jpg");
toy=new Toy("TurboS 1:24 Remote Control Benz SLS Licensed Toys Car, Red",imgSrcs,"cars and tracks","1049");
toys.push(toy);
imgSrcs=[];
imgSrcs.push("img/cars and tracks/hot_wheels_mega_hauler_1.jpg");
imgSrcs.push("img/cars and tracks/hot_wheels_mega_hauler_2.jpg");
imgSrcs.push("img/cars and tracks/hot_wheels_mega_hauler_3.jpg");
imgSrcs.push("img/cars and tracks/hot_wheels_mega_hauler_4.jpg");
imgSrcs.push("img/cars and tracks/hot_wheels_mega_hauler_5.jpg");
toy=new Toy("Hot Wheels Mega Hauler",imgSrcs,"cars and tracks","1110");
toys.push(toy);
imgSrcs=[];
imgSrcs.push("img/cars and tracks/avengers_age_of_ultron_cycle_blast_quinjet_vehicle_multi_color_1.jpg");
imgSrcs.push("img/cars and tracks/avengers_age_of_ultron_cycle_blast_quinjet_vehicle_multi_color_2.jpg");
imgSrcs.push("img/cars and tracks/avengers_age_of_ultron_cycle_blast_quinjet_vehicle_multi_color_3.jpg");
imgSrcs.push("img/cars and tracks/avengers_age_of_ultron_cycle_blast_quinjet_vehicle_multi_color_4.jpg");
imgSrcs.push("img/cars and tracks/avengers_age_of_ultron_cycle_blast_quinjet_vehicle_multi_color_5.jpg");
toy=new Toy("Avengers Age Of Ultron Cycle Blast Quinjet Vehicle Multi Color",imgSrcs,"cars and tracks","1359");
toys.push(toy);
imgSrcs=[];
imgSrcs.push("img/cars and tracks/turboz_tt652a_remote_control_changing_robot_car_orange_1.jpg");
imgSrcs.push("img/cars and tracks/turboz_tt652a_remote_control_changing_robot_car_orange_2.jpg");
imgSrcs.push("img/cars and tracks/turboz_tt652a_remote_control_changing_robot_car_orange_3.jpg");
imgSrcs.push("img/cars and tracks/turboz_tt652a_remote_control_changing_robot_car_orange_4.jpg");
toy=new Toy("TurboZ TT652A Remote Control Changing Robot Car Orange",imgSrcs,"cars and tracks","1609");
toys.push(toy);
imgSrcs=[];
imgSrcs.push("img/cars and tracks/thomas_friends_train_monkey_palace_set_1.jpg");
imgSrcs.push("img/cars and tracks/thomas_friends_train_monkey_palace_set_2.jpg");
imgSrcs.push("img/cars and tracks/thomas_friends_train_monkey_palace_set_3.jpg");
imgSrcs.push("img/cars and tracks/thomas_friends_train_monkey_palace_set_4.jpg");
imgSrcs.push("img/cars and tracks/thomas_friends_train_monkey_palace_set_5.jpg");
toy=new Toy("Thomas   Friends Train Monkey Palace Set",imgSrcs,"cars and tracks","1229");
toys.push(toy);
imgSrcs=[];
imgSrcs.push("img/cars and tracks/thomas_friends_thomas_friends_birthday_wish_thomas_train_playset_1.jpg");
imgSrcs.push("img/cars and tracks/thomas_friends_thomas_friends_birthday_wish_thomas_train_playset_2.jpg");
imgSrcs.push("img/cars and tracks/thomas_friends_thomas_friends_birthday_wish_thomas_train_playset_3.jpg");
imgSrcs.push("img/cars and tracks/thomas_friends_thomas_friends_birthday_wish_thomas_train_playset_4.jpg");
toy=new Toy("Thomas & Friends Birthday Wish Thomas Train Playset",imgSrcs,"cars and tracks","1639");
toys.push(toy);
//action figures
imgSrcs=[];
imgSrcs.push("img/action figures/toy_story_buzz_lightyear_figure-1.jpg");
imgSrcs.push("img/action figures/toy_story_buzz_lightyear_figure-2.jpg");
imgSrcs.push("img/action figures/toy_story_buzz_lightyear_figure-3.jpg");
imgSrcs.push("img/action figures/toy_story_buzz_lightyear_figure-4.jpg");
imgSrcs.push("img/action figures/toy_story_buzz_lightyear_figure-5.jpg");
toy=new Toy("Toy Story Buzz Lightyear Figure",imgSrcs,"action figures","669");
toys.push(toy);
imgSrcs=[];
imgSrcs.push("img/action figures/batman_365_6_basic_figure_night_jumper-1.jpg");
imgSrcs.push("img/action figures/batman_365_6_basic_figure_night_jumper-2.jpg");
imgSrcs.push("img/action figures/batman_365_6_basic_figure_night_jumper-3.jpg");
imgSrcs.push("img/action figures/batman_365_6_basic_figure_night_jumper-4.jpg");
imgSrcs.push("img/action figures/batman_365_6_basic_figure_night_jumper-5.jpg");
toy=new Toy("Batman 365 6 Basic Figure Night Jumper",imgSrcs,"action figures","659");
toys.push(toy);
imgSrcs=[];
imgSrcs.push("img/action figures/spider-man_figure_with_spider_cycle-1.jpg");
imgSrcs.push("img/action figures/spider-man_figure_with_spider_cycle-2.jpg");
toy=new Toy("Spider-man Figure With Spider Cycle",imgSrcs,"action figures","1599");
toys.push(toy);
imgSrcs=[];
imgSrcs.push("img/action figures/toy_story_woody_figure-1.jpg");
imgSrcs.push("img/action figures/toy_story_woody_figure-2.jpg");
imgSrcs.push("img/action figures/toy_story_woody_figure-3.jpg");
imgSrcs.push("img/action figures/toy_story_woody_figure-4.jpg");
toy=new Toy("Toy Story Woody Figure",imgSrcs,"action figures","669");
toys.push(toy);
imgSrcs=[];
imgSrcs.push("img/action figures/batman_missions_true-moves_figure_batman-1.jpg");
toy=new Toy("Batman Missions True-moves Figure Batman",imgSrcs,"action figures","819");
toys.push(toy);
imgSrcs=[];
imgSrcs.push("img/action figures/marvel_avengers_endgame_titan_hero_power_fx_black_panther-1.jpg");
imgSrcs.push("img/action figures/marvel_avengers_endgame_titan_hero_power_fx_black_panther-2.jpg");
toy=new Toy("Marvel Avengers Endgame Titan Hero Power Fx Black Panther",imgSrcs,"action figures","849");
toys.push(toy);
//doll, playsets and accessories
imgSrcs=[];
imgSrcs.push("img/dolls, playsets and accessories/barbie_career_doll_-_doctor_doll_1.jpg");
imgSrcs.push("img/dolls, playsets and accessories/barbie_career_doll_-_doctor_doll_2.jpg");
imgSrcs.push("img/dolls, playsets and accessories/barbie_career_doll_-_doctor_doll_3.jpg");
toy=new Toy("Barbie Career Doll-doctor Doll",imgSrcs,"dolls, playsets and accessories","599");
toys.push(toy);
imgSrcs=[];
imgSrcs.push("img/dolls, playsets and accessories/barbie_salon_doll_accessories_-_blonde_1.jpg");
imgSrcs.push("img/dolls, playsets and accessories/barbie_salon_doll_accessories_-_blonde_2.jpg");
imgSrcs.push("img/dolls, playsets and accessories/barbie_salon_doll_accessories_-_blonde_3.jpg");
imgSrcs.push("img/dolls, playsets and accessories/barbie_salon_doll_accessories_-_blonde_4.jpg");
toy=new Toy("Barbie Salon Doll Accessories - Blonde",imgSrcs,"dolls, playsets and accessories","1389");
toys.push(toy);
imgSrcs=[];
imgSrcs.push("img/dolls, playsets and accessories/barbie_ultimate_closet_doll_and_accessory_1.jpg");
imgSrcs.push("img/dolls, playsets and accessories/barbie_ultimate_closet_doll_and_accessory_2.jpg");
imgSrcs.push("img/dolls, playsets and accessories/barbie_ultimate_closet_doll_and_accessory_3.jpg");
imgSrcs.push("img/dolls, playsets and accessories/barbie_ultimate_closet_doll_and_accessory_4.jpg");
imgSrcs.push("img/dolls, playsets and accessories/barbie_ultimate_closet_doll_and_accessory_5.jpg");
toy=new Toy("Barbie Ultimate Closet Doll And Accessory",imgSrcs,"dolls, playsets and accessories","2099");
toys.push(toy);
imgSrcs=[];
imgSrcs.push("img/dolls, playsets and accessories/disney_frozen_sister_styles_elsa_fashion_doll_1.jpg");
imgSrcs.push("img/dolls, playsets and accessories/disney_frozen_sister_styles_elsa_fashion_doll_2.jpg");
imgSrcs.push("img/dolls, playsets and accessories/disney_frozen_sister_styles_elsa_fashion_doll_3.jpg");
imgSrcs.push("img/dolls, playsets and accessories/disney_frozen_sister_styles_elsa_fashion_doll_4.jpg");
toy=new Toy("Disney Frozen Sister Styles Elsa Fashion Doll",imgSrcs,"dolls, playsets and accessories","1289");
toys.push(toy);
imgSrcs=[];
imgSrcs.push("img/dolls, playsets and accessories/simba_steffi_love_animal_doctor-1.jpg");
imgSrcs.push("img/dolls, playsets and accessories/simba_steffi_love_animal_doctor-2.jpg");
imgSrcs.push("img/dolls, playsets and accessories/simba_steffi_love_animal_doctor-3.jpg");
toy=new Toy("Simba Steffi Love Animal Doctor",imgSrcs,"dolls, playsets and accessories","869");
toys.push(toy);
imgSrcs=[];
imgSrcs.push("img/dolls, playsets and accessories/barbie_career_doll_-_pop_star_doll_1.jpg");
imgSrcs.push("img/dolls, playsets and accessories/barbie_career_doll_-_pop_star_doll_2.jpg");
imgSrcs.push("img/dolls, playsets and accessories/barbie_career_doll_-_pop_star_doll_3.jpg");
toy=new Toy("Barbie Career Doll - Pop Star Doll",imgSrcs,"dolls, playsets and accessories","599");
toys.push(toy);
//guns and bullets
imgSrcs=[];
imgSrcs.push("img/guns and bullets/nerf_31-piece_alpha_strike_mission_ops_set_-1.jpg");
imgSrcs.push("img/guns and bullets/nerf_31-piece_alpha_strike_mission_ops_set_-2.jpg");
imgSrcs.push("img/guns and bullets/nerf_31-piece_alpha_strike_mission_ops_set_-3.jpg");
toy=new Toy("Nerf 31-piece Alpha Strike Mission Ops Set",imgSrcs,"guns and bullets","1599");
toys.push(toy);
imgSrcs=[];
imgSrcs.push("img/guns and bullets/nerf_megalodon_n-strike_mega_toy_blaster_1.jpg");
imgSrcs.push("img/guns and bullets/nerf_megalodon_n-strike_mega_toy_blaster_2.jpg");
imgSrcs.push("img/guns and bullets/nerf_megalodon_n-strike_mega_toy_blaster_3.jpg");
toy=new Toy("Nerf Megalodon N-strike Mega Toy Blaster",imgSrcs,"guns and bullets","3199");
toys.push(toy);
imgSrcs=[];
imgSrcs.push("img/guns and bullets/n-strike_elite_rough_cut_2x4_blaster_1.jpg");
imgSrcs.push("img/guns and bullets/n-strike_elite_rough_cut_2x4_blaster_2.jpg");
imgSrcs.push("img/guns and bullets/n-strike_elite_rough_cut_2x4_blaster_3.jpg");
imgSrcs.push("img/guns and bullets/n-strike_elite_rough_cut_2x4_blaster_4.jpg");
imgSrcs.push("img/guns and bullets/n-strike_elite_rough_cut_2x4_blaster_5.jpg");
toy=new Toy("N-strike Elite Rough Cut 2x4 Blaster",imgSrcs,"guns and bullets","1599");
toys.push(toy);
imgSrcs=[];
imgSrcs.push("img/guns and bullets/nerf_n-strike_elite_scout_mkii_1.jpg");
imgSrcs.push("img/guns and bullets/nerf_n-strike_elite_scout_mkii_2.jpg");
toy=new Toy("Nerf N-strike Elite Scout Mkii",imgSrcs,"guns and bullets","639");
toys.push(toy);
imgSrcs=[];
imgSrcs.push("img/guns and bullets/nerf_n-strike_elite_stryfe_blaster_1.jpg");
imgSrcs.push("img/guns and bullets/nerf_n-strike_elite_stryfe_blaster_2.jpg");
toy=new Toy("Nerf N-strike Elite Stryfe Blaster",imgSrcs,"guns and bullets","1599");
imgSrcs=[];
toys.push(toy);
imgSrcs.push("img/guns and bullets/nerf_n-strike_mega_doublebreach_blaster_1.jpg");
imgSrcs.push("img/guns and bullets/nerf_n-strike_mega_doublebreach_blaster_2.jpg");
imgSrcs.push("img/guns and bullets/nerf_n-strike_mega_doublebreach_blaster_3.jpg");
imgSrcs.push("img/guns and bullets/nerf_n-strike_mega_doublebreach_blaster_4.jpg");
toy=new Toy("Nerf N-strike Mega Doublebreach Blaster",imgSrcs,"guns and bullets","1999");
toys.push(toy);
imgSrcs=[];
imgSrcs.push("img/guns and bullets/nerf_n-strike_mega_series_rotofury_blaster_1.jpg");
imgSrcs.push("img/guns and bullets/nerf_n-strike_mega_series_rotofury_blaster_2.jpg");
imgSrcs.push("img/guns and bullets/nerf_n-strike_mega_series_rotofury_blaster_3.jpg");
toy=new Toy("N-strike Elite Rough Cut 2x4 Blaster",imgSrcs,"guns and bullets","2799");
toys.push(toy);
imgSrcs=[];
imgSrcs.push("img/guns and bullets/simba_planet_fighter_light_shooter_multi_color-1.jpg");
imgSrcs.push("img/guns and bullets/simba_planet_fighter_light_shooter_multi_color-2.jpg");
imgSrcs.push("img/guns and bullets/simba_planet_fighter_light_shooter_multi_color-3.jpg");
imgSrcs.push("img/guns and bullets/simba_planet_fighter_light_shooter_multi_color-4.jpg");
toy=new Toy("Simba Planet Fighter Light Shooter Multi Color",imgSrcs,"guns and bullets","749");
toys.push(toy);
imgSrcs=[];
imgSrcs.push("img/guns and bullets/nerf_n-strike_elite_universal_suction_dart_pack_of_12_1.jpg");
imgSrcs.push("img/guns and bullets/nerf_n-strike_elite_universal_suction_dart_pack_of_12_2.jpg");
toy=new Toy("Nerf N-strike Elite Universal Suction Dart Pack Of 12",imgSrcs,"guns and bullets","399");
toys.push(toy);
}
initializeToys();