function Cloth(name,category,imgSrcs,price)  //Constructor function
{
this.name=name;
this.category=category;
this.imgSrcs=imgSrcs;
this.price=price;
}
var clothes=[];
var cloth;
var imgSrcs=[];
// code to add clothes to collection
//polo shirts
imgSrcs.push("img/boys polo shirts/Boys Blue Printed Cotton Polo Shirt_1.jpg");
imgSrcs.push("img/boys polo shirts/Boys Blue Printed Cotton Polo Shirt_2.jpg");
imgSrcs.push("img/boys polo shirts/Boys Blue Printed Cotton Polo Shirt_3.jpg");
cloth=new Cloth("Boys Blue Printed Cotton Polo Shirt","polo shirts",imgSrcs,"240");
clothes.push(cloth);
imgSrcs=[];
imgSrcs.push("img/boys polo shirts/Boys Blue Short Sleeve Heathered Polo Shirt_1.jpg");
imgSrcs.push("img/boys polo shirts/Boys Blue Short Sleeve Heathered Polo Shirt_2.jpg");
imgSrcs.push("img/boys polo shirts/Boys Blue Short Sleeve Heathered Polo Shirt_3.jpg");
cloth=new Cloth("Boys Blue Short Sleeve Heathered Polo Shirt","polo shirts",imgSrcs,"240");
clothes.push(cloth);
imgSrcs=[];
imgSrcs.push("img/boys polo shirts/Boys Orange Printed Cotton Polo Shirt_1.jpg");
imgSrcs.push("img/boys polo shirts/Boys Orange Printed Cotton Polo Shirt_2.jpg");
cloth=new Cloth("Boys Orange Printed Cotton Polo Shirt","polo shirts",imgSrcs,"240");
clothes.push(cloth);
imgSrcs=[];
imgSrcs.push("img/boys polo shirts/Boys Blue Short Sleeve Printed Jersey Polo_1.jpg");
imgSrcs.push("img/boys polo shirts/Boys Blue Short Sleeve Printed Jersey Polo_2.jpg");
imgSrcs.push("img/boys polo shirts/Boys Blue Short Sleeve Printed Jersey Polo_3.jpg");
cloth=new Cloth("Boys Blue Short Sleeve Printed Jersey Polo","polo shirts",imgSrcs,"240");
clothes.push(cloth);
imgSrcs=[];
imgSrcs.push("img/boys polo shirts/Boys Green Short Sleeve Palm Print Polo_1.jpg");
imgSrcs.push("img/boys polo shirts/Boys Green Short Sleeve Palm Print Polo_2.jpg");
imgSrcs.push("img/boys polo shirts/Boys Green Short Sleeve Palm Print Polo_3.jpg");
cloth=new Cloth("Boys Green Short Sleeve Palm Print Polo","polo shirts",imgSrcs,"240");
clothes.push(cloth);
imgSrcs=[];
imgSrcs.push("img/boys polo shirts/Stupid Cupid Solid Half Sleeves Polo Tee - Red_1.jpg");
imgSrcs.push("img/boys polo shirts/Stupid Cupid Solid Half Sleeves Polo Tee - Red_2.jpg");
imgSrcs.push("img/boys polo shirts/Stupid Cupid Solid Half Sleeves Polo Tee - Red_3.jpg");
imgSrcs.push("img/boys polo shirts/Stupid Cupid Solid Half Sleeves Polo Tee - Red_4.jpg");
imgSrcs.push("img/boys polo shirts/Stupid Cupid Solid Half Sleeves Polo Tee - Red_5.jpg");
cloth=new Cloth("Stupid Cupid Solid Half Sleeves Polo Tee - Red","polo shirts",imgSrcs,"499");
clothes.push(cloth);

//t-shirts
imgSrcs=[];
imgSrcs.push("img/boys t-shirts/Babyhug Half Sleeves T-Shirts Shark Print Pack of 3 - White Navy Blue_1.jpg");
imgSrcs.push("img/boys t-shirts/Babyhug Half Sleeves T-Shirts Shark Print Pack of 3 - White Navy Blue_2.jpg");
imgSrcs.push("img/boys t-shirts/Babyhug Half Sleeves T-Shirts Shark Print Pack of 3 - White Navy Blue_3.jpg");
imgSrcs.push("img/boys t-shirts/Babyhug Half Sleeves T-Shirts Shark Print Pack of 3 - White Navy Blue_4.jpg");
cloth=new Cloth("Babyhug Half Sleeves T-Shirts Shark Print Pack of 3 - White Navy Blue","t-shirts",imgSrcs,"599");
clothes.push(cloth);
imgSrcs=[];
imgSrcs.push("img/boys t-shirts/Baobaoshu Half Sleeves Tee Crane Print - Blue_1.jpg");
imgSrcs.push("img/boys t-shirts/Baobaoshu Half Sleeves Tee Crane Print - Blue_2.jpg");
imgSrcs.push("img/boys t-shirts/Baobaoshu Half Sleeves Tee Crane Print - Blue_3.jpg");
imgSrcs.push("img/boys t-shirts/Baobaoshu Half Sleeves Tee Crane Print - Blue_4.jpg");
imgSrcs.push("img/boys t-shirts/Baobaoshu Half Sleeves Tee Crane Print - Blue_5.jpg");
cloth=new Cloth("Baobaoshu Half Sleeves Tee Crane Print - Blue","t-shirts",imgSrcs,"220");
clothes.push(cloth);
imgSrcs=[];
imgSrcs.push("img/boys t-shirts/Ollypop Half Sleeves Tee Text Print - Blue_1.jpg");
imgSrcs.push("img/boys t-shirts/Ollypop Half Sleeves Tee Text Print - Blue_2.jpg");
imgSrcs.push("img/boys t-shirts/Ollypop Half Sleeves Tee Text Print - Blue_3.jpg");
cloth=new Cloth("Ollypop Half Sleeves Tee Text Print - Blue","t-shirts",imgSrcs,"240");
clothes.push(cloth);
imgSrcs=[];
imgSrcs.push("img/boys t-shirts/Ollypop Half Sleeves Tee Text Print - Grey_1.jpg");
imgSrcs.push("img/boys t-shirts/Ollypop Half Sleeves Tee Text Print - Grey_2.jpg");
imgSrcs.push("img/boys t-shirts/Ollypop Half Sleeves Tee Text Print - Grey_3.jpg");
cloth=new Cloth("Ollypop Half Sleeves Tee Text Print - Grey","t-shirts",imgSrcs,"240");
clothes.push(cloth);
imgSrcs=[];
imgSrcs.push("img/boys t-shirts/Olio Kids Full Sleeves Solid Tee - Navy Blue_1.jpg");
imgSrcs.push("img/boys t-shirts/Olio Kids Full Sleeves Solid Tee - Navy Blue_2.jpg");
imgSrcs.push("img/boys t-shirts/Olio Kids Full Sleeves Solid Tee - Navy Blue_3.jpg");
imgSrcs.push("img/boys t-shirts/Olio Kids Full Sleeves Solid Tee - Navy Blue_4.jpg");
cloth=new Cloth("Olio Kids Full Sleeves Solid Tee - Navy Blue","t-shirts",imgSrcs,"240");
clothes.push(cloth);
imgSrcs=[];
imgSrcs.push("img/boys t-shirts/Baobaoshu Half Sleeves Tee Animal Print - White_1.jpg");
imgSrcs.push("img/boys t-shirts/Baobaoshu Half Sleeves Tee Animal Print - White_2.jpg");
imgSrcs.push("img/boys t-shirts/Baobaoshu Half Sleeves Tee Animal Print - White_3.jpg");
imgSrcs.push("img/boys t-shirts/Baobaoshu Half Sleeves Tee Animal Print - White_4.jpg");
cloth=new Cloth("Baobaoshu Half Sleeves Tee Animal Print - White","t-shirts",imgSrcs,"340");
clothes.push(cloth);imgSrcs=[];
imgSrcs.push("img/boys t-shirts/Babyhug Half Sleeves T-Shirt Spiderman Print - Red_3.jpg");
imgSrcs.push("img/boys t-shirts/Babyhug Half Sleeves T-Shirt Spiderman Print - Red_2.jpg");
imgSrcs.push("img/boys t-shirts/Babyhug Half Sleeves T-Shirt Spiderman Print - Red_1.jpg");
cloth=new Cloth("Babyhug Half Sleeves T-Shirt Spiderman Print - Red","t-shirts",imgSrcs,"240");
clothes.push(cloth);
//shorts
imgSrcs=[];
imgSrcs.push("img/boys shorts/Little Kangaroos Knee Length Shorts - White_1.jpg");
imgSrcs.push("img/boys shorts/Little Kangaroos Knee Length Shorts - White_2.jpg");
imgSrcs.push("img/boys shorts/Little Kangaroos Knee Length Shorts - White_3.jpg");
imgSrcs.push("img/boys shorts/Little Kangaroos Knee Length Shorts - White_4.jpg");
cloth=new Cloth("Little Kangaroos Knee Length Shorts - White","shorts",imgSrcs,"499");
clothes.push(cloth);
imgSrcs=[];
imgSrcs.push("img/boys shorts/Little Kangaroos Knee Length Shorts - Black_1.jpg");
imgSrcs.push("img/boys shorts/Little Kangaroos Knee Length Shorts - Black_2.jpg");
imgSrcs.push("img/boys shorts/Little Kangaroos Knee Length Shorts - Black_3.jpg");
imgSrcs.push("img/boys shorts/Little Kangaroos Knee Length Shorts - Black_4.jpg");
cloth=new Cloth("Little Kangaroos Knee Length Shorts - Black","shorts",imgSrcs,"499");
clothes.push(cloth);
imgSrcs=[];
imgSrcs.push("img/boys shorts/Olio Kids Denim Knee Length Jamaican Pants - Blue_1.jpg");
imgSrcs.push("img/boys shorts/Olio Kids Denim Knee Length Jamaican Pants - Blue_2.jpg");
imgSrcs.push("img/boys shorts/Olio Kids Denim Knee Length Jamaican Pants - Blue_3.jpg");
imgSrcs.push("img/boys shorts/Olio Kids Denim Knee Length Jamaican Pants - Blue_4.jpg");
cloth=new Cloth("Olio Kids Denim Knee Length Jamaican Pants - Blue","shorts",imgSrcs,"320");
clothes.push(cloth);
imgSrcs=[];
imgSrcs.push("img/boys shorts/Babyhug Shorts with Drawstring Car Print - Red_1.jpg");
imgSrcs.push("img/boys shorts/Babyhug Shorts with Drawstring Car Print - Red_2.jpg");
imgSrcs.push("img/boys shorts/Babyhug Shorts with Drawstring Car Print - Red_3.jpg");
imgSrcs.push("img/boys shorts/Babyhug Shorts with Drawstring Car Print - Red_4.jpg");
cloth=new Cloth("Babyhug Shorts with Drawstring Car Print - Red","shorts",imgSrcs,"290");
clothes.push(cloth);
imgSrcs=[];
imgSrcs.push("img/boys shorts/Babyoye Cotton Solid Shorts with Drawstring - Red_1.jpg");
imgSrcs.push("img/boys shorts/Babyoye Cotton Solid Shorts with Drawstring - Red_2.jpg");
imgSrcs.push("img/boys shorts/Babyoye Cotton Solid Shorts with Drawstring - Red_3.jpg");
cloth=new Cloth("Babyoye Cotton Solid Shorts with Drawstring - Red","shorts",imgSrcs,"629");
clothes.push(cloth);
imgSrcs=[];
imgSrcs.push("img/boys shorts/Babyhug Mid Thigh Length Shorts - Navy Blue_1.jpg");
imgSrcs.push("img/boys shorts/Babyhug Mid Thigh Length Shorts - Navy Blue_2.jpg");
imgSrcs.push("img/boys shorts/Babyhug Mid Thigh Length Shorts - Navy Blue_3.jpg");
cloth=new Cloth("Babyhug Mid Thigh Length Shorts - Navy Blue","shorts",imgSrcs,"320");
clothes.push(cloth);
;
//nightwear
imgSrcs=[];
imgSrcs.push("img/boys nightwear/Full Sleeve Night Suit Cloud Print_1.jpg");
imgSrcs.push("img/boys nightwear/Full Sleeve Night Suit Cloud Print_2.jpg");
imgSrcs.push("img/boys nightwear/Full Sleeve Night Suit Cloud Print_3.jpg");
imgSrcs.push("img/boys nightwear/Full Sleeve Night Suit Cloud Print_4.jpg");
cloth=new Cloth("Full Sleeve Night Suit Cloud Print","nightwear",imgSrcs,"800");
clothes.push(cloth);
imgSrcs=[];
imgSrcs.push("img/boys nightwear/Cucumber Sleeveless Night Suit Vehicle Print - Peach_1.jpg");
imgSrcs.push("img/boys nightwear/Cucumber Sleeveless Night Suit Vehicle Print - Peach_2.jpg");
imgSrcs.push("img/boys nightwear/Cucumber Sleeveless Night Suit Vehicle Print - Peach_3.jpg");
imgSrcs.push("img/boys nightwear/Cucumber Sleeveless Night Suit Vehicle Print - Peach_4.jpg");
imgSrcs.push("img/boys nightwear/Cucumber Sleeveless Night Suit Vehicle Print - Peach_5.jpg");
cloth=new Cloth("Cucumber Sleeveless Night Suit Vehicle Print - Peach","nightwear",imgSrcs,"1400");
clothes.push(cloth);
imgSrcs=[];
imgSrcs.push("img/boys nightwear/Cucumber Sleeveless Night Suit Vehicle Print - Sea Green_1.jpg");
imgSrcs.push("img/boys nightwear/Cucumber Sleeveless Night Suit Vehicle Print - Sea Green_2.jpg");
imgSrcs.push("img/boys nightwear/Cucumber Sleeveless Night Suit Vehicle Print - Sea Green_3.jpg");
imgSrcs.push("img/boys nightwear/Cucumber Sleeveless Night Suit Vehicle Print - Sea Green_4.jpg");
imgSrcs.push("img/boys nightwear/Cucumber Sleeveless Night Suit Vehicle Print - Sea Green_5.jpg");
cloth=new Cloth("Cucumber Sleeveless Night Suit Vehicle Print - Sea Green","nightwear",imgSrcs,"1400");
clothes.push(cloth);
imgSrcs=[];
imgSrcs.push("img/boys nightwear/Ollypop Full Sleeves Night Suit Multi Print - Light Grey_1.jpg");
imgSrcs.push("img/boys nightwear/Ollypop Full Sleeves Night Suit Multi Print - Light Grey_2.jpg");
imgSrcs.push("img/boys nightwear/Ollypop Full Sleeves Night Suit Multi Print - Light Grey_3.jpg");
imgSrcs.push("img/boys nightwear/Ollypop Full Sleeves Night Suit Multi Print - Light Grey_4.jpg");
cloth=new Cloth("Ollypop Full Sleeves Night Suit Multi Print - Light Grey","nightwear",imgSrcs,"1400");
clothes.push(cloth);
imgSrcs=[];
imgSrcs.push("img/boys nightwear/Ventra Quote Printed Full Sleeves Striped Night Suit - Navy Blue_1.jpg");
imgSrcs.push("img/boys nightwear/Ventra Quote Printed Full Sleeves Striped Night Suit - Navy Blue_2.jpg");
imgSrcs.push("img/boys nightwear/Ventra Quote Printed Full Sleeves Striped Night Suit - Navy Blue_3.jpg");
imgSrcs.push("img/boys nightwear/Ventra Quote Printed Full Sleeves Striped Night Suit - Navy Blue_4.jpg");
imgSrcs.push("img/boys nightwear/Ventra Quote Printed Full Sleeves Striped Night Suit - Navy Blue_5.jpg");
cloth=new Cloth("Ventra Quote Printed Full Sleeves Striped Night Suit - Navy Blue","nightwear",imgSrcs,"1200");
clothes.push(cloth);


//girls tops
imgSrcs=[];
imgSrcs.push("img/girls tops/Babyhug Flutter Sleeves Sequined Tee Minnie Mouse Print - White_1.jpg");
imgSrcs.push("img/girls tops/Babyhug Flutter Sleeves Sequined Tee Minnie Mouse Print - White_2.jpg");
imgSrcs.push("img/girls tops/Babyhug Flutter Sleeves Sequined Tee Minnie Mouse Print - White_3.jpg");
imgSrcs.push("img/girls tops/Babyhug Flutter Sleeves Sequined Tee Minnie Mouse Print - White_4.jpg");
cloth=new Cloth("Babyhug Flutter Sleeves Sequined Tee Minnie Mouse Print - White","girls tops",imgSrcs,"399");
clothes.push(cloth);
imgSrcs=[];
imgSrcs.push("img/girls tops/Babyhug Flutter Sleeves Tee Minnie Mouse Print - Pink_1.jpg");
imgSrcs.push("img/girls tops/Babyhug Flutter Sleeves Tee Minnie Mouse Print - Pink_2.jpg");
imgSrcs.push("img/girls tops/Babyhug Flutter Sleeves Tee Minnie Mouse Print - Pink_3.jpg");
cloth=new Cloth("Babyhug Flutter Sleeves Tee Minnie Mouse Print - Pink","girls tops",imgSrcs,"399");
clothes.push(cloth);
imgSrcs=[];
imgSrcs.push("img/girls tops/Babyoye Cotton Flutter Sleeves Top Butterfly Print - Pink_1.jpg");
imgSrcs.push("img/girls tops/Babyoye Cotton Flutter Sleeves Top Butterfly Print - Pink_2.jpg");
imgSrcs.push("img/girls tops/Babyoye Cotton Flutter Sleeves Top Butterfly Print - Pink_3.jpg");
cloth=new Cloth("Babyoye Cotton Flutter Sleeves Top Butterfly Print - Pink","girls tops",imgSrcs,"399");
clothes.push(cloth);
imgSrcs=[];
imgSrcs.push("img/girls tops/Ollypop Cap Sleeves T-Shirt Unicorn Patch - Pink_1.jpg");
imgSrcs.push("img/girls tops/Ollypop Cap Sleeves T-Shirt Unicorn Patch - Pink_2.jpg");
imgSrcs.push("img/girls tops/Ollypop Cap Sleeves T-Shirt Unicorn Patch - Pink_3.jpg");
cloth=new Cloth("Ollypop Cap Sleeves T-Shirt Unicorn Patch - Pink","girls tops",imgSrcs,"269");
clothes.push(cloth);
imgSrcs=[];
imgSrcs.push("img/girls tops/Babyoye Cotton Flutter Sleeves Top Heart Print - Blue_1.jpg");
imgSrcs.push("img/girls tops/Babyoye Cotton Flutter Sleeves Top Heart Print - Blue_2.jpg");
imgSrcs.push("img/girls tops/Babyoye Cotton Flutter Sleeves Top Heart Print - Blue_3.jpg");
cloth=new Cloth("Babyoye Cotton Flutter Sleeves Top Heart Print - Blue","girls tops",imgSrcs,"499");
clothes.push(cloth);
imgSrcs=[];
imgSrcs.push("img/girls tops/Babyhug Half Sleeves Top Floral Applique - Pink_1.jpg");
imgSrcs.push("img/girls tops/Babyhug Half Sleeves Top Floral Applique - Pink_2.jpg");
imgSrcs.push("img/girls tops/Babyhug Half Sleeves Top Floral Applique - Pink_3.jpg");
imgSrcs.push("img/girls tops/Babyhug Half Sleeves Top Floral Applique - Pink_4.jpg");
cloth=new Cloth("Babyhug Half Sleeves Top Floral Applique - Pink","girls tops",imgSrcs,"299");
clothes.push(cloth);
imgSrcs=[];
imgSrcs.push("img/girls tops/Meng Wa Half Sleeves Top Reindeer Print - Yellow_1.jpg");
imgSrcs.push("img/girls tops/Meng Wa Half Sleeves Top Reindeer Print - Yellow_2.jpg");
imgSrcs.push("img/girls tops/Meng Wa Half Sleeves Top Reindeer Print - Yellow_3.jpg");
imgSrcs.push("img/girls tops/Meng Wa Half Sleeves Top Reindeer Print - Yellow_4.jpg");
cloth=new Cloth("Meng Wa Half Sleeves Top Reindeer Print - Yellow","girls tops",imgSrcs,"499");
clothes.push(cloth);
imgSrcs=[];
imgSrcs.push("img/girls tops/Babyhug Ruffle Sleeves Top Mickey & Minnie Mouse Print - Grey_1.jpg");
imgSrcs.push("img/girls tops/Babyhug Ruffle Sleeves Top Mickey & Minnie Mouse Print - Grey_2.jpg");
imgSrcs.push("img/girls tops/Babyhug Ruffle Sleeves Top Mickey & Minnie Mouse Print - Grey_3.jpg");
imgSrcs.push("img/girls tops/Babyhug Ruffle Sleeves Top Mickey & Minnie Mouse Print - Grey_4.jpg");
cloth=new Cloth("Babyhug Ruffle Sleeves Top Mickey & Minnie Mouse Print - Grey","girls tops",imgSrcs,"349");
clothes.push(cloth);
imgSrcs=[];
imgSrcs.push("img/girls tops/Carter's Flutter Sleeves T-Shirt Floral Print - Blue_1.jpg");
imgSrcs.push("img/girls tops/Carter's Flutter Sleeves T-Shirt Floral Print - Blue_2.jpg");
cloth=new Cloth("Carter's Flutter Sleeves T-Shirt Floral Print - Blue","girls tops",imgSrcs,"880");
clothes.push(cloth);

//girls frocks
imgSrcs=[];
imgSrcs.push("img/girls frocks/Babyhug Sleeveless Party Frock Pearl Embellishments and Floral Print - Green_1.jpg");
imgSrcs.push("img/girls frocks/Babyhug Sleeveless Party Frock Pearl Embellishments and Floral Print - Green_2.jpg");
imgSrcs.push("img/girls frocks/Babyhug Sleeveless Party Frock Pearl Embellishments and Floral Print - Green_3.jpg");
imgSrcs.push("img/girls frocks/Babyhug Sleeveless Party Frock Pearl Embellishments and Floral Print - Green_4.jpg");
imgSrcs.push("img/girls frocks/Babyhug Sleeveless Party Frock Pearl Embellishments and Floral Print - Green_5.jpg");
imgSrcs.push("img/girls frocks/Babyhug Sleeveless Party Frock Pearl Embellishments and Floral Print - Green_6.jpg");
imgSrcs.push("img/girls frocks/Babyhug Sleeveless Party Frock Pearl Embellishments and Floral Print - Green_7.jpg");
cloth=new Cloth("Babyhug Sleeveless Party Frock Pearl Embellishments and Floral Print - Green","girls frocks",imgSrcs,"1529");
clothes.push(cloth);
imgSrcs=[];
imgSrcs.push("img/girls frocks/Enfance Cap Sleeves Bow Decorated Dots Self Design Flared Party Dress - Pink_1.jpg");
imgSrcs.push("img/girls frocks/Enfance Cap Sleeves Bow Decorated Dots Self Design Flared Party Dress - Pink_2.jpg");
imgSrcs.push("img/girls frocks/Enfance Cap Sleeves Bow Decorated Dots Self Design Flared Party Dress - Pink_3.jpg");
imgSrcs.push("img/girls frocks/Enfance Cap Sleeves Bow Decorated Dots Self Design Flared Party Dress - Pink_4.jpg");
imgSrcs.push("img/girls frocks/Enfance Cap Sleeves Bow Decorated Dots Self Design Flared Party Dress - Pink_5.jpg");
imgSrcs.push("img/girls frocks/Enfance Cap Sleeves Bow Decorated Dots Self Design Flared Party Dress - Pink_6.jpg");
cloth=new Cloth("Enfance Cap Sleeves Bow Decorated Dots Self Design Flared Party Dress - Pink","girls frocks",imgSrcs,"1299");
clothes.push(cloth);
imgSrcs=[];
imgSrcs.push("img/girls frocks/Kookie Kids Sleeveless Frock Floral Embroidery - Pink_1.jpg");
imgSrcs.push("img/girls frocks/Kookie Kids Sleeveless Frock Floral Embroidery - Pink_2.jpg");
imgSrcs.push("img/girls frocks/Kookie Kids Sleeveless Frock Floral Embroidery - Pink_3.jpg");
imgSrcs.push("img/girls frocks/Kookie Kids Sleeveless Frock Floral Embroidery - Pink_4.jpg");
cloth=new Cloth("Kookie Kids Sleeveless Frock Floral Embroidery - Pink","girls frocks",imgSrcs,"1390");
clothes.push(cloth);
imgSrcs=[];
imgSrcs.push("img/girls frocks/Maalka Sleeveless Flower Embellished Fit and Flare Dress With Belt - Peach_1.jpg");
imgSrcs.push("img/girls frocks/Maalka Sleeveless Flower Embellished Fit and Flare Dress With Belt - Peach_2.jpg");
imgSrcs.push("img/girls frocks/Maalka Sleeveless Flower Embellished Fit and Flare Dress With Belt - Peach_3.jpg");
imgSrcs.push("img/girls frocks/Maalka Sleeveless Flower Embellished Fit and Flare Dress With Belt - Peach_4.jpg");
imgSrcs.push("img/girls frocks/Maalka Sleeveless Flower Embellished Fit and Flare Dress With Belt - Peach_5.jpg");
imgSrcs.push("img/girls frocks/Maalka Sleeveless Flower Embellished Fit and Flare Dress With Belt - Peach_6.jpg");
imgSrcs.push("img/girls frocks/Maalka Sleeveless Flower Embellished Fit and Flare Dress With Belt - Peach_7.jpg");
cloth=new Cloth("Maalka Sleeveless Flower Embellished Fit and Flare Dress With Belt - Peach","girls frocks",imgSrcs,"1690");
clothes.push(cloth);
imgSrcs=[];
imgSrcs.push("img/girls frocks/Mark and Mia Flutter Sleeves Frock Floral Embroidered - Pink_1.jpg");
imgSrcs.push("img/girls frocks/Mark and Mia Flutter Sleeves Frock Floral Embroidered - Pink_2.jpg");
imgSrcs.push("img/girls frocks/Mark and Mia Flutter Sleeves Frock Floral Embroidered - Pink_3.jpg");
imgSrcs.push("img/girls frocks/Mark and Mia Flutter Sleeves Frock Floral Embroidered - Pink_4.jpg");
imgSrcs.push("img/girls frocks/Mark and Mia Flutter Sleeves Frock Floral Embroidered - Pink_5.jpg");
cloth=new Cloth("Mark and Mia Flutter Sleeves Frock Floral Embroidered - Pink","girls frocks",imgSrcs,"1800");
clothes.push(cloth);
imgSrcs=[];
imgSrcs.push("img/girls frocks/Mark and Mia Sleeveless Frock Flower Applique Embroidered - Cream_1.jpg");
imgSrcs.push("img/girls frocks/Mark and Mia Sleeveless Frock Flower Applique Embroidered - Cream_2.jpg");
imgSrcs.push("img/girls frocks/Mark and Mia Sleeveless Frock Flower Applique Embroidered - Cream_3.jpg");
imgSrcs.push("img/girls frocks/Mark and Mia Sleeveless Frock Flower Applique Embroidered - Cream_4.jpg");
imgSrcs.push("img/girls frocks/Mark and Mia Sleeveless Frock Flower Applique Embroidered - Cream_5.jpg");
cloth=new Cloth("Mark and Mia Sleeveless Frock Flower Applique Embroidered - Cream","girls frocks",imgSrcs,"1500");
clothes.push(cloth);

//girls jeans
imgSrcs=[];
imgSrcs.push("img/girls jeans/Girls Blue Distressed Denim Super Skinny Jeans_1.jpg");
imgSrcs.push("img/girls jeans/Girls Blue Distressed Denim Super Skinny Jeans_2.jpg");
imgSrcs.push("img/girls jeans/Girls Blue Distressed Denim Super Skinny Jeans_3.jpg");
cloth=new Cloth("Girls Blue Distressed Denim Super Skinny Jeans","girls jeans",imgSrcs,"1700");
clothes.push(cloth);
imgSrcs=[];
imgSrcs.push("img/girls jeans/Girls Blue Frayed Tulip Hem Super Skinny Jeans_1.jpg");
imgSrcs.push("img/girls jeans/Girls Blue Frayed Tulip Hem Super Skinny Jeans_2.jpg");
imgSrcs.push("img/girls jeans/Girls Blue Frayed Tulip Hem Super Skinny Jeans_3.jpg");
cloth=new Cloth("Girls Blue Frayed Tulip Hem Super Skinny Jeans","girls jeans",imgSrcs,"900");
clothes.push(cloth);
imgSrcs=[];
imgSrcs.push("img/girls jeans/Girls Blue Step Hem Distressed Denim Jeans_1.jpg");
imgSrcs.push("img/girls jeans/Girls Blue Step Hem Distressed Denim Jeans_2.jpg");
cloth=new Cloth("Girls Blue Step Hem Distressed Denim Jeans","girls jeans",imgSrcs,"1270");
clothes.push(cloth);
imgSrcs=[];
imgSrcs.push("img/girls jeans/Girls Blue Super Skinny Faded Jeans_1.jpg");
imgSrcs.push("img/girls jeans/Girls Blue Super Skinny Faded Jeans_2.jpg");
imgSrcs.push("img/girls jeans/Girls Blue Super Skinny Faded Jeans_3.jpg");
cloth=new Cloth("Girls Blue Super Skinny Faded Jeans","girls jeans",imgSrcs,"1300");
clothes.push(cloth);
imgSrcs=[];
imgSrcs.push("img/girls jeans/Levi's Girls' 711 Skinny Fit Jeans, Blue_1.jpg");
imgSrcs.push("img/girls jeans/Levi's Girls' 711 Skinny Fit Jeans, Blue_2.jpg");
imgSrcs.push("img/girls jeans/Levi's Girls' 711 Skinny Fit Jeans, Blue_3.jpg");
imgSrcs.push("img/girls jeans/Levi's Girls' 711 Skinny Fit Jeans, Blue_4.jpg");
cloth=new Cloth("Levi's Girls' 711 Skinny Fit Jeans, Blue","girls jeans",imgSrcs,"1400");
clothes.push(cloth);
imgSrcs=[];
imgSrcs.push("img/girls jeans/Polarn O. Pyret Children's Denim Jeans, Green_1.jpg");
imgSrcs.push("img/girls jeans/Polarn O. Pyret Children's Denim Jeans, Green_2.jpg");
imgSrcs.push("img/girls jeans/Polarn O. Pyret Children's Denim Jeans, Green_3.jpg");
cloth=new Cloth("Polarn O. Pyret Children's Denim Jeans, Green","girls jeans",imgSrcs,"1200");
clothes.push(cloth);
imgSrcs=[];
imgSrcs.push("img/girls jeans/Tommy Hilfiger Girls' Nora Skinny Denim Jeans, Denim_1.jpg");
imgSrcs.push("img/girls jeans/Tommy Hilfiger Girls' Nora Skinny Denim Jeans, Denim_2.jpg");
cloth=new Cloth("Tommy Hilfiger Girls' Nora Skinny Denim Jeans, Denim","girls jeans",imgSrcs,"1500");
clothes.push(cloth);
imgSrcs=[];
imgSrcs.push("img/girls jeans/White Stuff Girls' Hazel Jeggings, Denim_1.jpg");
imgSrcs.push("img/girls jeans/White Stuff Girls' Hazel Jeggings, Denim_2.jpg");
imgSrcs.push("img/girls jeans/White Stuff Girls' Hazel Jeggings, Denim_3.jpg");
cloth=new Cloth("White Stuff Girls' Hazel Jeggings, Denim","girls jeans",imgSrcs,"1250");
clothes.push(cloth);

//girls winterwear
imgSrcs=[];
imgSrcs.push("img/girls winterwear/Girls Regular Fit Hooded Printed Sweatshirt_1.jpg");
imgSrcs.push("img/girls winterwear/Girls Regular Fit Hooded Printed Sweatshirt_2.jpg");
imgSrcs.push("img/girls winterwear/Girls Regular Fit Hooded Printed Sweatshirt_3.jpg");
cloth=new Cloth("Girls Regular Fit Hooded Printed Sweatshirt","girls winterwear",imgSrcs,"1200");
clothes.push(cloth);
imgSrcs=[];
imgSrcs.push("img/girls winterwear/Girls Round Neck Graphic Print Sweatshirt_1.jpg");
imgSrcs.push("img/girls winterwear/Girls Round Neck Graphic Print Sweatshirt_2.jpg");
imgSrcs.push("img/girls winterwear/Girls Round Neck Graphic Print Sweatshirt_3.jpg");
cloth=new Cloth("Girls Round Neck Graphic Print Sweatshirt","girls winterwear",imgSrcs,"1460");
clothes.push(cloth);
imgSrcs=[];
imgSrcs.push("img/girls winterwear/Girls Round Neck Knitted Sweater_1.jpg");
imgSrcs.push("img/girls winterwear/Girls Round Neck Knitted Sweater_2.jpg");
imgSrcs.push("img/girls winterwear/Girls Round Neck Knitted Sweater_3.jpg");
cloth=new Cloth("Girls Round Neck Knitted Sweater","girls winterwear",imgSrcs,"600");
clothes.push(cloth);
imgSrcs=[];
imgSrcs.push("img/girls winterwear/Girls Round Neck Shimmer Sweatshirt_1.jpg");
imgSrcs.push("img/girls winterwear/Girls Round Neck Shimmer Sweatshirt_2.jpg");
imgSrcs.push("img/girls winterwear/Girls Round Neck Shimmer Sweatshirt_3.jpg");
cloth=new Cloth("Girls Round Neck Shimmer Sweatshirt","girls winterwear",imgSrcs,"1400");
clothes.push(cloth);
imgSrcs=[];
imgSrcs.push("img/girls winterwear/Girls Zip Through Neck Floral Print Sweatshirt_1.jpg");
imgSrcs.push("img/girls winterwear/Girls Zip Through Neck Floral Print Sweatshirt_2.jpg");
imgSrcs.push("img/girls winterwear/Girls Zip Through Neck Floral Print Sweatshirt_3.jpg");
cloth=new Cloth("Girls Zip Through Neck Floral Print Sweatshirt","girls winterwear",imgSrcs,"500");
clothes.push(cloth);
